version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04 #TODO
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: install#TODO 
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud